// ============================================
// Sample data seeded into Local Storage
// on first visit so the app is not empty.
// ============================================

export const sampleItems = [
  {
    id: 1,
    type: 'lost',
    title: 'AirPods Pro',
    category: 'Electronics',
    description: 'White AirPods Pro in a black case. Lost near the library entrance.',
    location: 'Library',
    date: '2026-08-20',
    image: '',
    status: 'Open',
    createdBy: 'Student',
    createdAt: '2026-08-20',
  },
  {
    id: 2,
    type: 'found',
    title: 'Student ID Card',
    category: 'Documents',
    description: 'Found a Chitkara University student ID card near Block A.',
    location: 'Block A',
    date: '2026-08-19',
    image: '',
    status: 'Open',
    createdBy: 'Student',
    createdAt: '2026-08-19',
  },
  {
    id: 3,
    type: 'lost',
    title: 'Blue Backpack',
    category: 'Bags',
    description: 'Navy blue Wildcraft backpack with laptop inside. Last seen in the cafeteria.',
    location: 'Cafeteria',
    date: '2026-08-18',
    image: '',
    status: 'Open',
    createdBy: 'Student',
    createdAt: '2026-08-18',
  },
  {
    id: 4,
    type: 'found',
    title: 'Silver Wristwatch',
    category: 'Accessories',
    description: 'Fossil silver wristwatch found on the bench near the sports complex.',
    location: 'Sports Complex',
    date: '2026-08-17',
    image: '',
    status: 'Claimed',
    createdBy: 'Student',
    createdAt: '2026-08-17',
  },
  {
    id: 5,
    type: 'lost',
    title: 'Calculus Textbook',
    category: 'Books',
    description: 'Thomas Calculus 14th Edition. Left in Block B, Room 204.',
    location: 'Block B',
    date: '2026-08-16',
    image: '',
    status: 'Open',
    createdBy: 'Student',
    createdAt: '2026-08-16',
  },
  {
    id: 6,
    type: 'found',
    title: 'Car Keys (Hyundai)',
    category: 'Keys',
    description: 'Hyundai car keys with a red keychain found in parking lot B.',
    location: 'Parking',
    date: '2026-08-15',
    image: '',
    status: 'Open',
    createdBy: 'Student',
    createdAt: '2026-08-15',
  },
  {
    id: 7,
    type: 'lost',
    title: 'Black Hoodie',
    category: 'Clothing',
    description: 'Plain black Nike hoodie, size L. Lost during the cultural fest at the auditorium.',
    location: 'Auditorium',
    date: '2026-08-14',
    image: '',
    status: 'Archived',
    createdBy: 'Student',
    createdAt: '2026-08-14',
  },
  {
    id: 8,
    type: 'found',
    title: 'Wireless Mouse',
    category: 'Electronics',
    description: 'Logitech wireless mouse found in the hostel common room.',
    location: 'Hostel',
    date: '2026-08-21',
    image: '',
    status: 'Open',
    createdBy: 'Student',
    createdAt: '2026-08-21',
  },
  {
    id: 9,
    type: 'lost',
    title: 'Prescription Glasses',
    category: 'Accessories',
    description: 'Black rectangular prescription glasses in a brown case.',
    location: 'Main Gate',
    date: '2026-08-22',
    image: '',
    status: 'Open',
    createdBy: 'Student',
    createdAt: '2026-08-22',
  },
  {
    id: 10,
    type: 'found',
    title: 'Umbrella',
    category: 'Other',
    description: 'Large black umbrella found at the main gate security desk.',
    location: 'Main Gate',
    date: '2026-08-23',
    image: '',
    status: 'Open',
    createdBy: 'Student',
    createdAt: '2026-08-23',
  },
];
